server:
  port: 8896
eureka:
  server:
    eviction-interval-timer-in-ms: 10000
    #enable-self-preservation: false
#    instance:
#      hostname: 39.106.212.226
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
