spring:
  application:
    name: intellect-book-gateway
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
  profiles:
    active: develop
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  ribbon:
    #开启饥饿模式
    eager-load:
      enabled: true
  routes:
    client:
    main-route:
      path: /main/**
      serviceId: docker-main
      #忽略前缀
      stripPrefix: false
    api-route:
      path: /docker/**
      serviceId: docker-api
      #忽略前缀
      stripPrefix: false
  max:
    host:
      connections: 500

  #ignored-services: '*'
#hystrix超时时间
#hystrix超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            ribbon:
              ReadTimeout: 60000
              ConnectTimeout: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true

